global:
  notificationSound: ''
  notificationPitch: 1.0
components:
  TownyComponent:
    enabled: true
  TownColorComponent:
    enabled: true
    useNationColors: true
    colorCount: 1
    towncolors:
      badlands:
      - Blue
      acoralis:
      - DarkPurple
    nationcolors: {}
  FlairComponent:
    enabled: true
    flairThreadURL: https://www.reddit.com/r/Chromagamers/comments/51ys94/flair_thread_for_the_mc_server/
  AnnouncerComponent:
    enabled: true
    announceMessages: []
    announceTime: 900000
  FunComponent:
    enabled: true
    laughStrings:
    - xd
    - lel
    - lawl
    - kek
    - lmao
    - hue
    - hah
    - rofl
    respect: true
    unlol: true
  AppendTextComponent:
    enabled: true
    texts:
      ww:
        helpText:
        - §6---- Wait what ----
        - Wait what
        appendedText: wait what
      lenny:
        helpText:
        - §6---- Lenny ----
        - This command appends a Lenny face after your message
        - Or just sends one
        appendedText: ( ͡° ͜ʖ ͡°)
      unflip:
        helpText:
        - §6---- Unflip ----
        - This command appends an unflip after your message
        - Or just unflips as you
        appendedText: ┬─┬ ノ( ゜-゜ノ)
      tableflip:
        helpText:
        - §6---- Tableflip ----
        - This command appends a tableflip after your message
        - Or just makes you tableflip
        appendedText: (╯°□°）╯︵ ┻━┻
      shrug:
        helpText:
        - §6---- Shrug ----
        - This command appends a shrug after your message
        - Or just makes you shrug
        appendedText: ¯\\\_(ツ)\_/¯
