global:
  notificationSound: ''
  notificationPitch: 1.0
  # If enabled, stores and displays the last 10 messages the player can see (public, their town chat etc.)
  # Can be used with the Discord plugin so players can see some of the conversation they missed that's visible on Discord anyways.
  storeChatHistory: true
components:
  # This component manages the town and nation chat. It's also needed for the TownColorComponent.
  # It provides the TC and NC channels, and posts Towny messages (global, town, nation) to the correct channels for other platforms like Discord.
  TownyComponent:
    enabled: true
  # Town colors for Towny. It allows mayors and kings to set a color for their town/nation (nation can be disabled).
  # This color is applied to the player names in chat and on Dynmap, if used.
  TownColorComponent:
    enabled: true
    useNationColors: true
    colorCount: 1
    towncolors:
      seedshire:
      - Blue
      liria:
      - DarkPurple
    nationcolors:
      leagueofcrafters: Gold
  # This component checks a specific Reddit thread every 10 seconds for comments such as "IGN: NorbiPeti" to link Reddit accounts and to determine their /r/thebutton flair.
  # This was the original goal of this plugin when it was made.
  FlairComponent:
    enabled: false
    flairThreadURL: https://www.reddit.com/r/Chromagamers/comments/51ys94/flair_thread_for_the_mc_server/
  # Displays the configured messages at the set interval when someone is online.
  AnnouncerComponent:
    enabled: true
    announceMessages:
    - §eCheck out the subreddit! https://www.reddit.com/r/Chromagamers/
    - '§bJoin Discord: https://discord.gg/gxmTS8N'
    - '§bLike the server? Vote: http://goo.gl/HDRW0a'
    announceTime: 900000
  # Random things I added over the years.
  FunComponent:
    enabled: true
    laughStrings:
    - xd
    - lel
    - lawl
    - kek
    - lmao
    - hue
    - hah
    - rofl
    respect: true
    unlol: true
  # Allows players to append tableflips and other things to their messages. Everything is configurable here.
  AppendTextComponent:
    enabled: true
    texts:
      waitwhat:
        helpText:
        - §6---- Wait what ----
        - Wait what
        appendedText: wait what
      lenny:
        helpText:
        - §6---- Lenny ----
        - This command appends a Lenny face after your message
        - Or just sends one
        appendedText: ( ͡° ͜ʖ ͡°)
      unflip:
        helpText:
        - §6---- Unflip ----
        - This command appends an unflip after your message
        - Or just unflips as you
        appendedText: ┬─┬ ノ( ゜-゜ノ)
      tableflip:
        helpText:
        - §6---- Tableflip ----
        - This command appends a tableflip after your message
        - Or just makes you tableflip
        appendedText: (╯°□°）╯︵ ┻━┻
      shrug:
        helpText:
        - §6---- Shrug ----
        - This command appends a shrug after your message
        - Or just makes you shrug
        appendedText: ¯\\\_(ツ)\_/¯
  # This component handles the custom processing of chat messages. If this component is disabled channels won't be supported in Minecraft.
  # If you only want to disable the formatting features, set allowFormatting to false.
  # If you're using another chat plugin, you should disable the whole component.
  FormatterComponent:
    enabled: true
    allowFormatting: true
    bold:
      enabled: true
    italic:
      enabled: true
    underlined:
      enabled: true
    strikethrough:
      enabled: true
    spoiler:
      enabled: true
    escape:
      enabled: true
    nullMention:
      enabled: true
    consolePing:
      enabled: true
    hashtag:
      enabled: true
    cyan:
      enabled: true
    code:
      enabled: true
    maskedLink:
      enabled: true
    url:
      enabled: true
    entireMessage:
      enabled: true
    name:
      enabled: true
    nickname:
      enabled: true
    italic2:
      enabled: true
    someone:
      enabled: true
    notificationSound: ''
    notificationPitch: 1.0
    rpc:
      enabled: true
    minTimeBetweenMessages: 100
