global:
  # If enabled, stores and displays the last 10 messages the player can see (public, their town chat etc.)
  # Can be used with the Discord plugin so players can see some of the conversation they missed that's visible on Discord anyways.
  storeChatHistory: true
components:
  # This component manages the town and nation chat. It's also needed for the TownColorComponent.
  # It provides the TC and NC channels, and posts Towny messages (global, town, nation) to the correct channels for other platforms like Discord.
  # You can disable /tc and /nc in Chroma-Core's config if you only want to use the TownColorComponent.
  TownyComponent:
    enabled: true
  # Town colors for Towny. It allows mayors and kings to set a color for their town/nation (nation can be disabled).
  # This color is applied to the player names in chat and on Dynmap, if used.
  TownColorComponent:
    enabled: true
    # If enabled, players will have a nation-defined color in addition to town colors, white by default.
    # They can change how much of each color they want with this as well.
    useNationColors: true
  # This component checks a specific Reddit thread every 10 seconds for comments such as "IGN: NorbiPeti" to link Reddit accounts and to determine their /r/thebutton flair.
  # This was the original goal of this plugin when it was made.
  FlairComponent:
    enabled: false
  # Displays the configured messages at the set interval when someone is online.
  AnnouncerComponent:
    enabled: false
    # The messages to display to players.
    announceMessages:
    - §eCheck out the subreddit! https://www.reddit.com/r/Chromagamers/
    - '§bJoin Discord: https://discord.gg/gxmTS8N'
    - '§bLike the server? Vote: http://goo.gl/HDRW0a'
    # The time in milliseconds between the messages. Use /u announce settime to set minutes.
    announceTime: 900000
  # Random things I added over the years.
  FunComponent:
    enabled: true
    # This is an inside joke on our server.
    # It keeps track of laughs (lols and what's defined in laughStrings) and if someone does /unlol or /unlaugh it will unlaugh the last person who laughed.
    # Which also blinds the laughing person for a few seconds. This action can only be performed once per laugh.
    unlol: true
    # The strings that count as laughs, see unlol.
    laughStrings:
    - xd
    - lel
    - lawl
    - kek
    - lmao
    - hue
    - hah
    - rofl
    # The "Press F to pay respects" meme in Minecraft. It will randomly appear on player death and keep track of how many "F"s are said in chat.
    # You can hover over a player's name to see their respect.
    respect: true
  # Allows players to append tableflips and other things to their messages. Everything is configurable here.
  AppendTextComponent:
    enabled: true
    texts:
      lenny:
        helpText:
        - §6---- Lenny ----
        - This command appends a Lenny face after your message
        - Or just sends one
        appendedText: ( ͡° ͜ʖ ͡°)
      unflip:
        helpText:
        - §6---- Unflip ----
        - This command appends an unflip after your message
        - Or just unflips as you
        appendedText: ┬─┬ ノ( ゜-゜ノ)
      waitwhat:
        helpText:
        - §6---- Wait what ----
        - Wait what
        appendedText: wait what
      tableflip:
        helpText:
        - §6---- Tableflip ----
        - This command appends a tableflip after your message
        - Or just makes you tableflip
        appendedText: (╯°□°）╯︵ ┻━┻
      shrug:
        helpText:
        - §6---- Shrug ----
        - This command appends a shrug after your message
        - Or just makes you shrug
        appendedText: ¯\\\_(ツ)\_/¯
  # This component handles the custom processing of chat messages. If this component is disabled channels won't be supported in Minecraft.
  # If you only want to disable the formatting features, set allowFormatting to false.
  # If you're using another chat plugin, you should disable the whole component but that will make it impossible to use channels.
  FormatterComponent:
    enabled: true
    # The minimum time between messages in milliseconds.
    minTimeBetweenMessages: 100
    # Determines whether Markdown formatting, name mentioning and similar features are enabled.
    allowFormatting: true
    nickname:
      enabled: true
    name:
      enabled: true
    bold:
      enabled: true
    italic:
      enabled: true
    underlined:
      enabled: true
    italic2:
      enabled: true
    strikethrough:
      enabled: true
    spoiler:
      enabled: true
    nullMention:
      enabled: true
    consolePing:
      enabled: true
    cyan:
      enabled: true
    code:
      enabled: true
    maskedLink:
      enabled: true
    url:
      enabled: true
    hashtag:
      enabled: true
    someone:
      enabled: true
    greentext:
      enabled: true
