Chairs:
- WOOD_STAIRS
- SPRUCE_WOOD_STAIRS
- JUNGLE_WOOD_STAIRS
- BIRCH_WOOD_STAIRS
- SANDSTONE_STAIRS
- COBBLESTONE_STAIRS
- BRICK_STAIRS
- SMOOTH_STAIRS
- NETHER_BRICK_STAIRS
- QUARTZ_STAIRS
- ACACIA_STAIRS
- DARK_OAK_STAIRS
- ANDESITE_STAIRS
- DARK_PRISMARINE_STAIRS
- DIORITE_STAIRS
- END_STONE_BRICK_STAIRS
- GRANITE_STAIRS
- MOSSY_COBBLESTONE_STAIRS
- MOSSY_STONE_BRICK_STAIRS
- POLISHED_ANDESITE_STAIRS
- POLISHED_DIORITE_STAIRS
- POLISHED_GRANITE_STAIRS
- PRISMARINE_BRICK_STAIRS
- PRISMARINE_STAIRS
- PURPUR_STAIRS
- QUARTZ_STAIRS
- RED_NETHER_BRICK_STAIRS
- RED_SANDSTONE_STAIRS
- SMOOTH_QUARTZ_STAIRS
- SMOOTH_RED_SANDSTONE_STAIRS
- SMOOTH_SANDSTONE_STAIRS
UpsideDown: false
Range: 0
