global:
  commandChannel: 209720707188260864
  prefix: /
  mainServer: 125813020357165056
  modRole: Moderator
  test: false
  inviteLink: https://discord.gg/9V57sTZ
components:
  GeneralEventBroadcasterModule:
    enabled: true
  MinecraftChatModule:
    enabled: true
    chatChannel: 249663564057411596
    chcons:
      '477963575068196875':
        mcchid: dev
        chid: 477963575068196875
        did: 126012419792306177
        mcuid: bd0c72e7-f5a6-49be-a407-ad69e72a3431
        mcname: NorbiPeti
        groupid: everyone
        toggles: 0
        brtoggles: []
    whitelistedCommands:
    - list
    - u
    - shrug
    - tableflip
    - unflip
    - mwiki
    - yeehaw
    - lenny
    - rp
    - plugins
    - press
    excludedPlugins:
    - ProtocolLib
    - LibsDisguises
    - JourneyMapServer
    allowFakePlayerTeleports: false
    showPlayerListOnDC: true
    allowCustomChat: true
    allowPrivateChat: true
  ExceptionListenerModule:
    enabled: true
    channel: 239519012529111040
    pingRole: 282291454326603776
  GameRoleModule:
    enabled: true
    logChannel: 283840717275791360
  AnnouncerModule:
    enabled: true
    lastAnnouncementTime: 1563726352
    lastSeenTime: 1563726352
    keepPinned: 40
    channel: 125813020357165056
    modChannel: 126795071927353344
  FunModule:
    enabled: true
    fullHouseChannel: 219626707458457603
    fullHouseDevRole: 219594051178070017
    serverReadyAnswers:
    - In one week from now
    - Between now and the heat-death of the universe.
    - Soon™
    - Ask again this time next month
    - In about 3 seconds
    - After we finish 8 plugins
    - Tomorrow.
    - After one tiiiny feature
    - Next commit
    - After we finish strangling Towny
    - When we kill every *fucking* bug
    - Once the server stops screaming.
    - After HL3 comes out
    - Next time you ask
    - When will *you* be open?
    serverReady:
    - when will the server be open
    - when will the server be ready
    - when will the server be done
    - when will the server be complete
    - when will the server be finished
    - when's the server ready
    - when's the server open
    - Vhen vill ze server be open?
serverup: true
