components:
  DictionaryComponent:
    enabled: true
  SpawnComponent:
    enabled: true
  MagicComponent:
    enabled: true
  ResearchComponent:
    enabled: true
  TownyFactionsComponent:
    enabled: true
    distance: 5
  PortalLimitComponent:
    enabled: true
    worlds:
    - v1
    - v2
    - v3
