test: false
global:
  writePluginList: true
components:
  PluginUpdaterComponent:
    enabled: true
  RestartComponent:
    enabled: true
  ChannelComponent:
    enabled: true
    g:
      enabled: true
      IDs:
      - ooc
      color: White
      displayName: §fOOC§f
    a:
      enabled: true
      IDs: []
    mod:
      enabled: true
      IDs: []
      color: Blue
      displayName: §9MOD§f
    dev:
      enabled: true
      IDs: []
    red:
      enabled: true
      IDs: []
    orange:
      enabled: true
      IDs: []
    yellow:
      enabled: true
      IDs: []
    green:
      enabled: true
      IDs: []
    blue:
      enabled: true
      IDs: []
    purple:
      enabled: true
      IDs: []
    tc:
      enabled: true
      IDs: []
    nc:
      enabled: true
      IDs: []
      color: Gold
      displayName: §6NC§f
    rp:
      enabled: true
      IDs: []
  RandomTPComponent:
    enabled: true
  MemberComponent:
    enabled: true
    memberGroup: member
  TownyComponent:
    enabled: true
