global:
  # Sets whether the plugin should write a list of installed plugins in a txt file.
  # It can be useful if some other software needs to know the plugins.
  writePluginList: false
  # Print some debug information.
  test: false
  # The chat format to use for messages from other platforms if Chroma-Chat is not installed.
  chatFormat: '[{origin}|{channel}] <{name}> {message}'
  # If a Chroma command clashes with another plugin's command, this setting determines whether the Chroma command should be executed or the other plugin's.
  prioritizeCustomCommands: false
components:
  # Provides commands such as /schrestart (restart after a countdown) and /primerestart (restart when nobody is online).
  # Also can automatically restart at a given time.
  RestartComponent:
    enabled: true
    # Specifies the hour of day when the server should be restarted. Set to -1 to disable.
    restartAt: -1
  # Manages chat channels. If disabled, only global channels will be registered.
  ChannelComponent:
    enabled: true
    g:
      enabled: true
      displayName: §fg§f
      color: White
      IDs: []
    a:
      enabled: true
      displayName: §cADMIN§f
      color: Red
      IDs: []
    mod:
      enabled: true
      displayName: §9MOD§f
      color: Blue
      IDs: []
    dev:
      enabled: true
      displayName: §6DEV§f
      color: Gold
      IDs: []
    red:
      enabled: true
      displayName: §cRED§f
      color: DarkRed
      IDs: []
    orange:
      enabled: true
      displayName: §6ORANGE§f
      color: Gold
      IDs: []
    yellow:
      enabled: true
      displayName: §eYELLOW§f
      color: Yellow
      IDs: []
    green:
      enabled: true
      displayName: §aGREEN§f
      color: Green
      IDs: []
    blue:
      enabled: true
      displayName: §bBLUE§f
      color: Blue
      IDs: []
    purple:
      enabled: true
      displayName: §5PURPLE§f
      color: DarkPurple
      IDs: []
    tc:
      enabled: true
      displayName: §3TC§f
      color: DarkAqua
      IDs: []
    nc:
      enabled: true
      displayName: §6NC§f
      color: Gold
      IDs: []
    rp:
      enabled: true
      displayName: §7RP§f
      color: Gray
      IDs: []
  # Teleport player to random location within world border.
  # Every five players teleport to the same general area, and then a new general area is randomly selected for the next five players.
  # Author: github.com/iiegit
  RandomTPComponent:
    enabled: false
  # Allows giving a 'member' group over some time elapsed OR played.
  MemberComponent:
    enabled: false
  # Provides a /spawn command that works with BungeeCord. Make sure to set up on each server.
  SpawnComponent:
    enabled: false
  # Provides a command to remove invalid Towny residents.
  TownyComponent:
    enabled: true
