global:
  # Sets whether the plugin should write a list of installed plugins in a txt file.
  # It can be useful if some other software needs to know the plugins.
  writePluginList: true
  # Print some debug information.
  test: false
  # The chat format to use for messages from other platforms if Chroma-Chat is not installed.
  chatFormat: '[{origin}|{channel}] <{name}> {message}'
  # If a Chroma command clashes with another plugin's command, this setting determines whether the Chroma command should be executed or the other plugin's.
  prioritizeCustomCommands: false
components:
  PluginUpdaterComponent:
    enabled: true
  # Provides commands such as /schrestart (restart after a countdown) and /primerestart (restart when nobody is online).
  # Also can automatically restart at a given time.
  RestartComponent:
    enabled: true
    # Specifies the hour of day when the server should be restarted. Set to -1 to disable.
    restartAt: 12
  # Manages chat channels. If disabled, only global channels will be registered.
  ChannelComponent:
    enabled: true
    g:
      enabled: true
      IDs: []
      displayName: §fg§f
      color: White
    a:
      enabled: true
      IDs: []
      displayName: §cADMIN§f
      color: Red
    mod:
      enabled: true
      IDs: []
      displayName: §9MOD§f
      color: Blue
    dev:
      enabled: true
      IDs: []
      displayName: §6DEV§f
      color: Gold
    red:
      enabled: true
      IDs: []
      displayName: §cRED§f
      color: DarkRed
    orange:
      enabled: true
      IDs: []
      displayName: §6ORANGE§f
      color: Gold
    yellow:
      enabled: true
      IDs: []
      displayName: §eYELLOW§f
      color: Yellow
    green:
      enabled: true
      IDs: []
      displayName: §aGREEN§f
      color: Green
    blue:
      enabled: true
      IDs: []
      displayName: §bBLUE§f
      color: Blue
    purple:
      enabled: true
      IDs: []
      displayName: §5PURPLE§f
      color: DarkPurple
    tc:
      enabled: true
      IDs: []
      displayName: §3TC§f
      color: DarkAqua
    nc:
      enabled: true
      IDs: []
      displayName: §6NC§f
      color: Gold
    rp:
      enabled: true
      IDs: []
      displayName: §7RP§f
      color: Gray
  # Teleport player to random location within world border.
  # Every five players teleport to the same general area, and then a new general area is randomly selected for the next five players.
  # Author: github.com/iiegit
  RandomTPComponent:
    enabled: false
  # Allows giving a 'member' group over some time elapsed OR played.
  MemberComponent:
    enabled: true
    # The amount of days passed since first login
    registeredForDays: 7
    # The amount of hours needed to play before promotion
    playedHours: 12
    # The permission group to give to the player
    memberGroup: member
  # Provides a command to remove invalid Towny residents.
  TownyComponent:
    enabled: false
  VotifierComponent:
    enabled: true
    rewardAmount: 0.0
  # Provides a /spawn command that works with BungeeCord. Make sure to set up on each server.
  SpawnComponent:
    enabled: true
    # The BungeeCord server that has the spawn. Set to empty if this server is the target.
    targetServer: ''
