test: false
global:
  writePluginList: true
  test: false
  chatFormat: '[{origin}|{channel}] <{name}> {message}'
components:
  PluginUpdaterComponent:
    enabled: true
  RestartComponent:
    enabled: true
  ChannelComponent:
    enabled: true
    g:
      enabled: true
      IDs:
      - ooc
      color: White
      displayName: §fOOC§f
    a:
      enabled: true
      IDs: []
    mod:
      enabled: true
      IDs: []
      color: Blue
      displayName: §9MOD§f
    dev:
      enabled: true
      IDs: []
      displayName: §6DEV§f
      color: Gold
    red:
      enabled: true
      IDs: []
    orange:
      enabled: true
      IDs: []
    yellow:
      enabled: true
      IDs: []
    green:
      enabled: true
      IDs: []
    blue:
      enabled: true
      IDs: []
    purple:
      enabled: true
      IDs: []
    tc:
      enabled: true
      IDs: []
      displayName: §3TC§f
      color: DarkAqua
    nc:
      enabled: true
      IDs: []
      color: Gold
      displayName: §6NC§f
    rp:
      enabled: true
      IDs: []
      displayName: §7RP§f
      color: Gray
  RandomTPComponent:
    enabled: true
  MemberComponent:
    enabled: true
    memberGroup: member
    registeredForDays: 7
    playedHours: 12
  TownyComponent:
    enabled: true
  VotifierComponent:
    enabled: true
    rewardAmount: 0.0
  SpawnComponent:
    enabled: true
    targetServer: lobby
