global:
  writePluginList: true
  test: false
  chatFormat: '[{origin}|{channel}] <{name}> {message}'
components:
  PluginUpdaterComponent:
    enabled: true
  RestartComponent:
    enabled: true
  ChannelComponent:
    enabled: true
    g:
      enabled: true
      IDs: []
      displayName: §fg§f
      color: White
    a:
      enabled: true
      IDs: []
    mod:
      enabled: true
      IDs: []
      displayName: §9MOD§f
      color: Blue
    dev:
      enabled: true
      IDs: []
      displayName: §6DEV§f
      color: Gold
    red:
      enabled: true
      IDs: []
    orange:
      enabled: true
      IDs: []
    yellow:
      enabled: true
      IDs: []
    green:
      enabled: true
      IDs: []
    blue:
      enabled: true
      IDs: []
    purple:
      enabled: true
      IDs: []
    tc:
      enabled: true
      IDs: []
      displayName: §3TC§f
      color: DarkAqua
    nc:
      enabled: true
      IDs: []
      displayName: §6NC§f
      color: Gold
    rp:
      enabled: true
      IDs: []
  RandomTPComponent:
    enabled: false
  MemberComponent:
    enabled: true
    registeredForDays: 7
    playedHours: 12
    memberGroup: member
  TownyComponent:
    enabled: true
  VotifierComponent:
    enabled: true
    rewardAmount: 0.0
  SpawnComponent:
    enabled: true
    targetServer: ''
