configuration_version: v5
worlds:
  plotworld:
    plot:
      height: 62
      biome: minecraft:forest
      size: 42
      filling: stone:100
      auto_merge: false
      bedrock: true
      create_signs: true
      floor: grass_block:100
    wall:
      filling: stone:100
      block_claimed: sandstone_slab:100
      height: 62
      block: stone_slab:100
      place_top_block: true
    misc_spawn_unowned: false
    road:
      block: quartz_block:100
      height: 62
      width: 7
      flags: {}
    home:
      nonmembers: side
      default: side
    schematic:
      specify_on_claim: false
      on_claim: false
      file: 'null'
      schematics: []
    economy:
      prices:
        merge: 100
        sell: 100
        claim: 100
      use: false
    chat:
      enabled: false
      forced: false
    limits:
      max-members: 128
    world:
      max_height: 256
      gamemode: creative
      min_height: 1
      border: false
    event:
      spawn:
        egg: false
        breeding: false
        custom: true
    natural_mob_spawning: false
    mob_spawner_spawning: false
    flags: {}
